export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    STUDENTS: '/admin/users',
    TEACHERS: '/admin/users',
    COURSES: '/admin/courses',
    ENROLLMENTS: '/admin/enrollments',
    ATTENDANCE: '/admin/attendance',
    NOTES: '/admin/notes',
    FEES: '/admin/fees',
    USER_DETAIL: '/admin/users/:id',
    EMAIL: '/admin/email',
    PROFILE: '/admin/profile',
    SETTINGS: '/admin/settings',
  },
  TEACHER: {
    DASHBOARD: '/teacher/dashboard',
    COURSES: '/teacher/courses',
    ATTENDANCE: '/teacher/attendance',
    NOTES: '/teacher/notes',
    EMAIL: '/teacher/email',
    PROFILE: '/teacher/profile',
    SETTINGS: '/teacher/settings',
  },
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    COURSES: '/student/courses',
    ATTENDANCE: '/student/attendance',
    NOTES: '/student/notes',
    FEES: '/student/fees',
    PROFILE: '/student/profile',
    SETTINGS: '/student/settings',
  },
};
